apps:
  - name: HTTP server
    scheme: http
    port: 8080
    host: "localhost"
    working-directory: /home/coder
    icon-path: /home/coder/python.png
    command: python3
    args: ["-m", "SimpleHTTPServer"]
    health-check:
      exec:
        command: "pgrep"
        args: ["python3"]